#!/usr/bin/env bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} close-all
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && nautilus ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && nautilus ~/Dokumente &

elif [[ "$1" == "--music" ]]; then
	close_dash && nautilus ~/Musik &

elif [[ "$1" == "--pics" ]]; then
	close_dash && nautilus ~/Bilder &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && nautilus ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && nautilus ~/.local/share &

elif [[ "$1" == "--home" ]]; then
	close_dash && nautilus ~ &

elif [[ "$1" == "--videos" ]]; then
	close_dash && nautilus ~/Videos &

fi
